# This file was auto-generated by Fern from our API Definition.

from . import company, contact, deal, event, field_mapping, lead, note, properties, proxy, task, user
from .company import (
    CreateOrUpdateCompanyRequest,
    CreateOrUpdateCompanyResponse,
    GetCompaniesResponse,
    GetCompanyResponse,
    SearchCompaniesResponse,
)
from .contact import (
    CreateOrUpdateContactRequest,
    CreateOrUpdateContactResponse,
    GetContactResponse,
    GetContactsResponse,
    SearchContactsResponse,
)
from .deal import (
    CreateOrUpdateDealRequest,
    CreateOrUpdateDealResponse,
    GetDealResponse,
    GetDealsResponse,
    SearchDealsResponse,
)
from .event import (
    CreateOrUpdateEventRequest,
    CreateOrUpdateEventResponse,
    DeleteEventResponse,
    GetEventResponse,
    GetEventsResponse,
    SearchEventsResponse,
)
from .lead import (
    CreateOrUpdateLeadRequest,
    CreateOrUpdateLeadResponse,
    GetLeadResponse,
    GetLeadsResponse,
    SearchLeadsResponse,
)
from .note import (
    CreateOrUpdateNoteRequest,
    CreateOrUpdateNoteResponse,
    GetNoteResponse,
    GetNotesResponse,
    SearchNotesResponse,
)
from .properties import (
    FieldDetailsType,
    FieldDetailsTypeRequest,
    GetObjectPropertiesResponse,
    SetObjectPropertiesRequest,
    SetObjectPropertiesResponse,
)
from .proxy import PostProxyRequestBody, ProxyResponse
from .task import (
    CreateOrUpdateTaskRequest,
    CreateOrUpdateTaskResponse,
    GetTaskResponse,
    GetTasksResponse,
    SearchTasksResponse,
)
from .user import CreateOrUpdateUserRequest, CreateOrUpdateUserResponse, GetUserResponse, GetUsersResponse

__all__ = [
    "CreateOrUpdateCompanyRequest",
    "CreateOrUpdateCompanyResponse",
    "CreateOrUpdateContactRequest",
    "CreateOrUpdateContactResponse",
    "CreateOrUpdateDealRequest",
    "CreateOrUpdateDealResponse",
    "CreateOrUpdateEventRequest",
    "CreateOrUpdateEventResponse",
    "CreateOrUpdateLeadRequest",
    "CreateOrUpdateLeadResponse",
    "CreateOrUpdateNoteRequest",
    "CreateOrUpdateNoteResponse",
    "CreateOrUpdateTaskRequest",
    "CreateOrUpdateTaskResponse",
    "CreateOrUpdateUserRequest",
    "CreateOrUpdateUserResponse",
    "DeleteEventResponse",
    "FieldDetailsType",
    "FieldDetailsTypeRequest",
    "GetCompaniesResponse",
    "GetCompanyResponse",
    "GetContactResponse",
    "GetContactsResponse",
    "GetDealResponse",
    "GetDealsResponse",
    "GetEventResponse",
    "GetEventsResponse",
    "GetLeadResponse",
    "GetLeadsResponse",
    "GetNoteResponse",
    "GetNotesResponse",
    "GetObjectPropertiesResponse",
    "GetTaskResponse",
    "GetTasksResponse",
    "GetUserResponse",
    "GetUsersResponse",
    "PostProxyRequestBody",
    "ProxyResponse",
    "SearchCompaniesResponse",
    "SearchContactsResponse",
    "SearchDealsResponse",
    "SearchEventsResponse",
    "SearchLeadsResponse",
    "SearchNotesResponse",
    "SearchTasksResponse",
    "SetObjectPropertiesRequest",
    "SetObjectPropertiesResponse",
    "company",
    "contact",
    "deal",
    "event",
    "field_mapping",
    "lead",
    "note",
    "properties",
    "proxy",
    "task",
    "user",
]
