# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.candidate.client import AsyncCandidateClient, CandidateClient
from .resources.department.client import AsyncDepartmentClient, DepartmentClient
from .resources.job.client import AsyncJobClient, JobClient
from .resources.offer.client import AsyncOfferClient, OfferClient
from .resources.proxy.client import AsyncProxyClient, ProxyClient


class AtsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.candidate = CandidateClient(client_wrapper=self._client_wrapper)
        self.department = DepartmentClient(client_wrapper=self._client_wrapper)
        self.job = JobClient(client_wrapper=self._client_wrapper)
        self.offer = OfferClient(client_wrapper=self._client_wrapper)
        self.proxy = ProxyClient(client_wrapper=self._client_wrapper)


class AsyncAtsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.candidate = AsyncCandidateClient(client_wrapper=self._client_wrapper)
        self.department = AsyncDepartmentClient(client_wrapper=self._client_wrapper)
        self.job = AsyncJobClient(client_wrapper=self._client_wrapper)
        self.offer = AsyncOfferClient(client_wrapper=self._client_wrapper)
        self.proxy = AsyncProxyClient(client_wrapper=self._client_wrapper)
