# This file was auto-generated by Fern from our API Definition.

from .types import (
    FieldDetailsType,
    FieldDetailsTypeRequest,
    GetObjectPropertiesResponse,
    SetObjectPropertiesRequest,
    SetObjectPropertiesResponse,
)

__all__ = [
    "FieldDetailsType",
    "FieldDetailsTypeRequest",
    "GetObjectPropertiesResponse",
    "SetObjectPropertiesRequest",
    "SetObjectPropertiesResponse",
]
