# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.collection.client import AsyncCollectionClient, CollectionClient
from .resources.comment.client import AsyncCommentClient, CommentClient
from .resources.proxy.client import AsyncProxyClient, ProxyClient
from .resources.task.client import AsyncTaskClient, TaskClient
from .resources.user.client import AsyncUserClient, UserClient


class TicketClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.collection = CollectionClient(client_wrapper=self._client_wrapper)
        self.comment = CommentClient(client_wrapper=self._client_wrapper)
        self.proxy = ProxyClient(client_wrapper=self._client_wrapper)
        self.task = TaskClient(client_wrapper=self._client_wrapper)
        self.user = UserClient(client_wrapper=self._client_wrapper)


class AsyncTicketClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.collection = AsyncCollectionClient(client_wrapper=self._client_wrapper)
        self.comment = AsyncCommentClient(client_wrapper=self._client_wrapper)
        self.proxy = AsyncProxyClient(client_wrapper=self._client_wrapper)
        self.task = AsyncTaskClient(client_wrapper=self._client_wrapper)
        self.user = AsyncUserClient(client_wrapper=self._client_wrapper)
