# This file was auto-generated by Fern from our API Definition.

from .....common.resources.unified.types.comment_ticket_write import CommentTicketWrite

CreateOrUpdateCommentRequest = CommentTicketWrite
