# This file was auto-generated by Fern from our API Definition.

from .types import (
    CreateOrUpdateDepartmentRequest,
    CreateOrUpdateDepartmentResponse,
    DeleteDepartmentResponse,
    GetDepartmentResponse,
    GetDepartmentsResponse,
)

__all__ = [
    "CreateOrUpdateDepartmentRequest",
    "CreateOrUpdateDepartmentResponse",
    "DeleteDepartmentResponse",
    "GetDepartmentResponse",
    "GetDepartmentsResponse",
]
