# This file was auto-generated by Fern from our API Definition.

from .types import CreateorUpdateMessageRequest, CreateorUpdateMessageResponse

__all__ = ["CreateorUpdateMessageRequest", "CreateorUpdateMessageResponse"]
