# This file was auto-generated by Fern from our API Definition.

from .....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.field_mapping.client import (
    AsyncFieldMappingClient as resources_crm_resources_field_mapping_resources_field_mapping_client_AsyncFieldMappingClient,
)
from .resources.field_mapping.client import (
    FieldMappingClient as resources_crm_resources_field_mapping_resources_field_mapping_client_FieldMappingClient,
)


class FieldMappingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.field_mapping = resources_crm_resources_field_mapping_resources_field_mapping_client_FieldMappingClient(
            client_wrapper=self._client_wrapper
        )


class AsyncFieldMappingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.field_mapping = (
            resources_crm_resources_field_mapping_resources_field_mapping_client_AsyncFieldMappingClient(
                client_wrapper=self._client_wrapper
            )
        )
