# This file was auto-generated by Fern from our API Definition.

from .create_or_update_department_request import CreateOrUpdateDepartmentRequest
from .create_or_update_department_response import CreateOrUpdateDepartmentResponse
from .delete_department_response import DeleteDepartmentResponse
from .get_department_response import GetDepartmentResponse
from .get_departments_response import GetDepartmentsResponse

__all__ = [
    "CreateOrUpdateDepartmentRequest",
    "CreateOrUpdateDepartmentResponse",
    "DeleteDepartmentResponse",
    "GetDepartmentResponse",
    "GetDepartmentsResponse",
]
