# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConnectionStatus(str, enum.Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

    def visit(self, success: typing.Callable[[], T_Result], failed: typing.Callable[[], T_Result]) -> T_Result:
        if self is ConnectionStatus.SUCCESS:
            return success()
        if self is ConnectionStatus.FAILED:
            return failed()
