# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TicketPriority(str, enum.Enum):
    URGENT = "urgent"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    LOWEST = "lowest"

    def visit(
        self,
        urgent: typing.Callable[[], T_Result],
        high: typing.Callable[[], T_Result],
        medium: typing.Callable[[], T_Result],
        low: typing.Callable[[], T_Result],
        lowest: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is TicketPriority.URGENT:
            return urgent()
        if self is TicketPriority.HIGH:
            return high()
        if self is TicketPriority.MEDIUM:
            return medium()
        if self is TicketPriority.LOW:
            return low()
        if self is TicketPriority.LOWEST:
            return lowest()
