# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Tpid(str, enum.Enum):
    HUBSPOT = "hubspot"
    ZOHOCRM = "zohocrm"
    SFDC = "sfdc"
    PIPEDRIVE = "pipedrive"
    SLACK = "slack"

    def visit(
        self,
        hubspot: typing.Callable[[], T_Result],
        zohocrm: typing.Callable[[], T_Result],
        sfdc: typing.Callable[[], T_Result],
        pipedrive: typing.Callable[[], T_Result],
        slack: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Tpid.HUBSPOT:
            return hubspot()
        if self is Tpid.ZOHOCRM:
            return zohocrm()
        if self is Tpid.SFDC:
            return sfdc()
        if self is Tpid.PIPEDRIVE:
            return pipedrive()
        if self is Tpid.SLACK:
            return slack()
