# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.company.client import AsyncCompanyClient, CompanyClient
from .resources.contact.client import AsyncContactClient, ContactClient
from .resources.deal.client import AsyncDealClient, DealClient
from .resources.event.client import AsyncEventClient, EventClient
from .resources.field_mapping.client import AsyncFieldMappingClient, FieldMappingClient
from .resources.lead.client import AsyncLeadClient, LeadClient
from .resources.note.client import AsyncNoteClient, NoteClient
from .resources.properties.client import AsyncPropertiesClient, PropertiesClient
from .resources.proxy.client import AsyncProxyClient, ProxyClient
from .resources.task.client import AsyncTaskClient, TaskClient
from .resources.user.client import AsyncUserClient, UserClient


class CrmClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.company = CompanyClient(client_wrapper=self._client_wrapper)
        self.contact = ContactClient(client_wrapper=self._client_wrapper)
        self.deal = DealClient(client_wrapper=self._client_wrapper)
        self.event = EventClient(client_wrapper=self._client_wrapper)
        self.field_mapping = FieldMappingClient(client_wrapper=self._client_wrapper)
        self.lead = LeadClient(client_wrapper=self._client_wrapper)
        self.note = NoteClient(client_wrapper=self._client_wrapper)
        self.properties = PropertiesClient(client_wrapper=self._client_wrapper)
        self.proxy = ProxyClient(client_wrapper=self._client_wrapper)
        self.task = TaskClient(client_wrapper=self._client_wrapper)
        self.user = UserClient(client_wrapper=self._client_wrapper)


class AsyncCrmClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.company = AsyncCompanyClient(client_wrapper=self._client_wrapper)
        self.contact = AsyncContactClient(client_wrapper=self._client_wrapper)
        self.deal = AsyncDealClient(client_wrapper=self._client_wrapper)
        self.event = AsyncEventClient(client_wrapper=self._client_wrapper)
        self.field_mapping = AsyncFieldMappingClient(client_wrapper=self._client_wrapper)
        self.lead = AsyncLeadClient(client_wrapper=self._client_wrapper)
        self.note = AsyncNoteClient(client_wrapper=self._client_wrapper)
        self.properties = AsyncPropertiesClient(client_wrapper=self._client_wrapper)
        self.proxy = AsyncProxyClient(client_wrapper=self._client_wrapper)
        self.task = AsyncTaskClient(client_wrapper=self._client_wrapper)
        self.user = AsyncUserClient(client_wrapper=self._client_wrapper)
