# This file was auto-generated by Fern from our API Definition.

from . import candidate, department, job, offer, proxy
from .candidate import (
    CreateOrUpdateCandidateRequest,
    CreateOrUpdateCandidateResponse,
    DeleteCandidateResponse,
    GetCandidateResponse,
    GetCandidatesResponse,
)
from .department import (
    CreateOrUpdateDepartmentRequest,
    CreateOrUpdateDepartmentResponse,
    DeleteDepartmentResponse,
    GetDepartmentResponse,
    GetDepartmentsResponse,
)
from .job import CreateOrUpdateJobRequest, CreateOrUpdateJobResponse, DeleteJobResponse, GetJobResponse, GetJobsResponse
from .offer import (
    CreateOrUpdateOfferRequest,
    CreateOrUpdateOfferResponse,
    DeleteOfferResponse,
    GetOfferResponse,
    GetOffersResponse,
)
from .proxy import PostProxyRequestBody, ProxyResponse

__all__ = [
    "CreateOrUpdateCandidateRequest",
    "CreateOrUpdateCandidateResponse",
    "CreateOrUpdateDepartmentRequest",
    "CreateOrUpdateDepartmentResponse",
    "CreateOrUpdateJobRequest",
    "CreateOrUpdateJobResponse",
    "CreateOrUpdateOfferRequest",
    "CreateOrUpdateOfferResponse",
    "DeleteCandidateResponse",
    "DeleteDepartmentResponse",
    "DeleteJobResponse",
    "DeleteOfferResponse",
    "GetCandidateResponse",
    "GetCandidatesResponse",
    "GetDepartmentResponse",
    "GetDepartmentsResponse",
    "GetJobResponse",
    "GetJobsResponse",
    "GetOfferResponse",
    "GetOffersResponse",
    "PostProxyRequestBody",
    "ProxyResponse",
    "candidate",
    "department",
    "job",
    "offer",
    "proxy",
]
