# This file was auto-generated by Fern from our API Definition.

import typing

from .field_details_type_read import FieldDetailsTypeRead

GetObjectPropertiesResponse = typing.List[FieldDetailsTypeRead]
