# This file was auto-generated by Fern from our API Definition.

from .create_or_update_candidate_request import CreateOrUpdateCandidateRequest
from .create_or_update_candidate_response import CreateOrUpdateCandidateResponse
from .delete_candidate_response import DeleteCandidateResponse
from .get_candidate_response import GetCandidateResponse
from .get_candidates_response import GetCandidatesResponse

__all__ = [
    "CreateOrUpdateCandidateRequest",
    "CreateOrUpdateCandidateResponse",
    "DeleteCandidateResponse",
    "GetCandidateResponse",
    "GetCandidatesResponse",
]
