# This file was auto-generated by Fern from our API Definition.

import enum


class RevertEnvironment(enum.Enum):
    PRODUCTION = "https://api.revert.dev"
    STAGING = "https://api-staging.revert.dev"
    """
    This staging environment is helpful for testing!
    """

    LOCAL = "http://localhost:4001"
